"""
Massive neutrinos, integrating momentum with CAMB's sparse stencils.
"""

import equinox as eqx
import jax.numpy as jnp
from jax import vmap
from jax.typing import ArrayLike
from jaxtyping import Array

from .. import constants as cnst
from . import adiabatic_ics
from .base import Fluid, FluidParams, OutputArgs, PerturbationContext

# CAMB's tuned momentum stencils (massive_neutrinos.f90), the default rules:
# nodes q_i and kernel weights w_i satisfying, with f0(q) = 1/(e^q + 1),
#
#   (1/4) * int dq q^2 f0(q) F(q)  ~=  sum_i w_i (1+e^{-q_i}) F(q_i)/q_i^2
#
# (the 1/4 is cancelled by the 4/pi^2 prefactors in the integrals that use
# them). The weights fold the q^2 f0 measure into themselves, which is why
# every integrand carries the compensating (1 + e^{-q})/q^2 factor.
#
# Generated by moment-matching against the perturbation kernel
# q^4 * (-df0/dq): Howlett, Lewis, Hall & Challinor (arXiv:1201.3654),
# Appendix A. Both constructions are vendored in _camb_stencil_generation.py
# and pinned by test: the 3-point rule is the unique moment match n = -4..2;
# the 5-point rule is CAMB's original background rule (nodes 2, 4, 13 fixed
# by choice, the rest moment-matched to n = -4..3; since replaced upstream
# by a refit, kept here for continuity). ABCMB's last 5-point weight carries
# 0.12681 for CAMB's 0.126817 (historical transcription, dropped digit).
_CAMB_Q_PERT = (0.913201, 3.37517, 7.79184)
_CAMB_W_PERT = (0.0687359, 3.31435, 2.29911)
_CAMB_Q_BG = (0.583165, 2.0, 4.0, 7.26582, 13.0)
_CAMB_W_BG = (0.0081201, 0.689407, 2.8063, 2.05156, 0.12681)


class MassiveNeutrino(Fluid):
    """
    Non-relativistic neutrinos with multiple angular momentum modes.

    Notes
    -----
    The sparse momentum quadrature (q_pert/w_pert for the evolved bins,
    q_bg/w_bg for background rho/P) replaces MB95's dense q-grid with CAMB's
    tuned 3- and 5-point stencils.
    """

    num_ells_per_bin: int = eqx.field(default=0, static=True)
    q_pert: tuple = eqx.field(default=_CAMB_Q_PERT, static=True)
    w_pert: tuple = eqx.field(default=_CAMB_W_PERT, static=True)
    q_bg: tuple = eqx.field(default=_CAMB_Q_BG, static=True)
    w_bg: tuple = eqx.field(default=_CAMB_W_BG, static=True)

    name = "MassiveNeutrino"
    is_matter = True
    is_neutrino = True

    def __init__(self, first_idx, options):

        super().__init__(first_idx, options)
        self.num_ells_per_bin = options["l_max_massive_nu"] + 1
        self.q_pert, self.w_pert = _CAMB_Q_PERT, _CAMB_W_PERT
        self.q_bg, self.w_bg = _CAMB_Q_BG, _CAMB_W_BG
        self.num_equations = len(self.q_pert) * self.num_ells_per_bin

    def _dlnf0_dlnq_pert(self) -> Array:
        # d(ln f0)/d(ln q) at the perturbation nodes, for the Fermi-Dirac f0:
        # the metric-source coupling of the Psi hierarchy and its initial
        # conditions (MB95 Eqs. 56 and 97) are written in terms of this.
        q = jnp.asarray(self.q_pert)
        return -q / (1.0 + jnp.exp(-q))

    def rho(self, lna: ArrayLike, args: FluidParams) -> Array | float:
        """
        Compute massive neutrino density.

        Returns:
           Massive neutrino density (units: eV cm^{-3})
        """
        params = args

        # Ensure lna is at least 1D for broadcasting
        lna_arr = jnp.atleast_1d(lna)  # shape (N,)
        # shape (N,1):
        a = jnp.exp(lna_arr)[:, None]
        T = params["T_nu_massive"] * params["TCMB0"] / a
        x = params["m_nu_massive"] / T

        # q_bg is shape (n_bg,), broadcast with (N, 1)
        q = jnp.asarray(self.q_bg)
        integrand = (1.0 + jnp.exp(-q)) / q**2 * jnp.sqrt(q**2 + x**2)  # (N, n_bg)

        # Dot product along last axis with the kernel weights
        integral = jnp.dot(integrand, jnp.asarray(self.w_bg))  # (N,)

        rho_val = (
            params["N_nu_massive"]
            * 4.0
            * T[:, 0] ** 4
            / jnp.pi**2
            * integral
            / cnst.hbar**3
            / cnst.c**3
        )

        # Remove extra dimension if original input was scalar
        return jnp.squeeze(rho_val) if jnp.ndim(lna) == 0 else rho_val

    def P(self, lna: ArrayLike, args: FluidParams) -> Array | float:
        """
        Compute massive neutrino pressure.

        Returns:
           Massive neutrino pressure (units: eV cm^{-3})
        """
        params = args

        # Ensure lna is at least 1D for broadcasting
        lna_arr = jnp.atleast_1d(lna)  # shape (N,)
        # shape (N,1)
        a = jnp.exp(lna_arr)[:, None]
        T = params["T_nu_massive"] * params["TCMB0"] / a
        x = params["m_nu_massive"] / T

        # q_bg is shape (n_bg,), broadcast with (N, 1)
        q = jnp.asarray(self.q_bg)
        integrand = (1.0 + jnp.exp(-q)) / jnp.sqrt(q**2 + x**2)  # (N, n_bg)

        # Dot product along last axis with the kernel weights
        integral = jnp.dot(integrand, jnp.asarray(self.w_bg))  # (N,)

        P_val = (
            params["N_nu_massive"]
            * 4.0
            / 3.0
            * T[:, 0] ** 4
            / jnp.pi**2
            * integral
            / cnst.hbar**3
            / cnst.c**3
        )

        # Remove extra dimension if original input was scalar
        return jnp.squeeze(P_val) if jnp.ndim(lna) == 0 else P_val

    def y_ini(self, k: ArrayLike, tau_ini: ArrayLike, args: FluidParams) -> Array:
        """
        Adiabatic initial conditions: at tau_ini the neutrinos are
        ultra-relativistic, so the fluid content is the massless-neutrino
        one (shared series in :mod:`.adiabatic_ics`), mapped onto the
        per-node Psi_l via MB95 Eq. (97) (epsilon/q -> 1 at early times).

        Returns:
            Initial perturbation mode values (units: 1/Mpc for kPsi1, else dimensionless)
        """
        params = args

        delta = adiabatic_ics.delta_gamma(k, tau_ini, params)
        theta = adiabatic_ics.theta_nu(k, tau_ini, params)
        sigma = adiabatic_ics.sigma_nu(k, tau_ini, params)

        dlnf0_dlnq = self._dlnf0_dlnq_pert()
        bins = []
        for i in range(len(self.q_pert)):
            # MB95 Eq. (97): (Psi0, kPsi1, Psi2) = -(delta/4, theta/3, sigma/2)
            # * dlnf0/dlnq.
            # ZZ : Techniclly Psi1 requires epsilon/q = 1/v, but at early times this should be 1. Should check this accuracy!
            first_three = (
                -jnp.array([delta / 4.0, theta / 3.0, sigma / 2.0]) * dlnf0_dlnq[i]
            )
            bins.append(
                jnp.concatenate((first_three, jnp.zeros(self.num_ells_per_bin - 3)))
            )

        return jnp.concatenate(bins)

    def y_prime(
        self,
        k: ArrayLike,
        lna: ArrayLike,
        metric_h_prime: ArrayLike,
        metric_eta_prime: ArrayLike,
        y: Array,
        args: PerturbationContext,
    ) -> Array:
        """
        Compute time derivatives of massive neutrino perturbations.
        Follows Ma & Bertschinger (1995), ApJ 455, 7 (arXiv:astro-ph/9506072).
        The per-momentum-bin Psi_l hierarchy is their Eq. (56), truncated with
        their Eq. (58);
        the momentum-integrated delta/theta/sigma perturbations
        are their Eq. (55);
        Returns:
            Time derivatives of perturbation modes (units: 1/Mpc for kPsi1, else dimensionless)
        """
        BG, params = args.BG, args.params

        a = jnp.exp(lna)
        T = params["T_nu_massive"] * params["TCMB0"] / a
        x = params["m_nu_massive"] / T
        aH = BG.aH(lna, params)
        tau = BG.tau(lna)

        # Iterate through momentum bins
        q_nodes = jnp.asarray(self.q_pert)
        dlnf0_arr = self._dlnf0_dlnq_pert()
        bins = []
        for i in range(len(self.q_pert)):
            q = q_nodes[i]
            epsilon = jnp.sqrt(q**2 + x**2)
            dlnf0_dlnq = dlnf0_arr[i]

            # NOTE: The entries are [Psi0, k * Psi1, Psi2, ...]. If accessing Psi1 make sure to divide out k
            L = (
                jnp.arange(self.num_ells_per_bin)
                + self.first_idx
                + i * self.num_ells_per_bin
            )
            Psi = y[L]

            Psi0_prime = -q / epsilon / aH * Psi[1] + metric_h_prime / 6.0 * dlnf0_dlnq
            kPsi1_prime = q * k**2 / 3.0 / epsilon / aH * (Psi[0] - 2.0 * Psi[2])
            Psi2_prime = (
                q * k / 5.0 / epsilon / aH * (2.0 * Psi[1] / k - 3.0 * Psi[3])
                - (metric_h_prime / 15.0 + 2.0 * metric_eta_prime / 5.0) * dlnf0_dlnq
            )

            # Intermediate hierarchy, 3<=L<lmax
            lmax = self.num_ells_per_bin - 1
            L_inter = jnp.arange(3, lmax)  # Doesn't include lmax.
            Psi_inter_prime = (
                q
                * k
                / epsilon
                / aH
                / (2 * L_inter + 1)
                * (L_inter * Psi[L_inter - 1] - (L_inter + 1) * Psi[L_inter + 1])
            )

            # lmax mode
            Psi_lmax_prime = (
                q * k / aH / epsilon * Psi[lmax - 1] - (lmax + 1) / aH / tau * Psi[lmax]
            )

            # Putting it all together
            bins.append(
                jnp.concatenate(
                    (
                        jnp.array([Psi0_prime, kPsi1_prime, Psi2_prime]),
                        Psi_inter_prime,
                        jnp.array([Psi_lmax_prime]),
                    )
                )
            )

        return jnp.concatenate(bins)

    def rho_delta(
        self, lna: ArrayLike, y: Array, args: PerturbationContext
    ) -> Array | float:
        """
        Compute massive neutrino density perturbation.

        Returns:
           Density perturbation (units: eV cm^{-3})
        """
        return self._rho_delta(lna, y, args.params)

    def _rho_delta(
        self, lna: ArrayLike, y: Array, params: FluidParams
    ) -> Array | float:
        a = jnp.exp(lna)
        T = params["T_nu_massive"] * params["TCMB0"] / a  # (N,)
        x = params["m_nu_massive"] / T  # (N,)

        q_nodes = jnp.asarray(self.q_pert)
        w_nodes = jnp.asarray(self.w_pert)
        res = 0.0
        for i in range(len(self.q_pert)):
            q = q_nodes[i]
            w = w_nodes[i]
            epsilon = jnp.sqrt(q**2 + x**2)
            Psi0 = y[self.first_idx + i * self.num_ells_per_bin]

            res += w * (1.0 + jnp.exp(-q)) * epsilon / q**2 * Psi0
        return (
            params["N_nu_massive"]
            * res
            * 4.0
            / jnp.pi**2
            * T**4
            / cnst.hbar**3
            / cnst.c**3
        )

    def rho_plus_P_theta(
        self, lna: ArrayLike, y: Array, args: PerturbationContext
    ) -> Array | float:
        """
        Compute massive neutrino velocity perturbation.

        Returns:
            Velocity perturbation (units: eV cm^{-3} Mpc^{-1})
        """
        return self._rho_plus_P_theta(lna, y, args.params)

    def _rho_plus_P_theta(
        self, lna: ArrayLike, y: Array, params: FluidParams
    ) -> Array | float:
        a = jnp.exp(lna)
        T = params["T_nu_massive"] * params["TCMB0"] / a  # (N,)

        q_nodes = jnp.asarray(self.q_pert)
        w_nodes = jnp.asarray(self.w_pert)
        res = 0.0
        for i in range(len(self.q_pert)):
            q = q_nodes[i]
            w = w_nodes[i]
            kPsi1 = y[self.first_idx + 1 + i * self.num_ells_per_bin]

            res += w * (1.0 + jnp.exp(-q)) / q * kPsi1
        return (
            params["N_nu_massive"]
            * res
            * 4.0
            / jnp.pi**2
            * T**4
            / cnst.hbar**3
            / cnst.c**3
        )

    def rho_plus_P_sigma(
        self, lna: ArrayLike, y: Array, args: PerturbationContext
    ) -> Array | float:
        """
        Compute massive neutrino shear perturbation.

        Returns:
            Shear perturbation (units: eV cm^{-3})
        """
        return self._rho_plus_P_sigma(lna, y, args.params)

    def _rho_plus_P_sigma(
        self, lna: ArrayLike, y: Array, params: FluidParams
    ) -> Array | float:
        a = jnp.exp(lna)
        T = params["T_nu_massive"] * params["TCMB0"] / a  # (N,)
        x = params["m_nu_massive"] / T  # (N,)

        q_nodes = jnp.asarray(self.q_pert)
        w_nodes = jnp.asarray(self.w_pert)
        res = 0.0
        for i in range(len(self.q_pert)):
            q = q_nodes[i]
            w = w_nodes[i]
            epsilon = jnp.sqrt(q**2 + x**2)
            Psi2 = y[self.first_idx + 2 + i * self.num_ells_per_bin]

            res += w * (1.0 + jnp.exp(-q)) / epsilon * Psi2
        return (
            params["N_nu_massive"]
            * res
            * 8.0
            / 3.0
            / jnp.pi**2
            * T**4
            / cnst.hbar**3
            / cnst.c**3
        )

    def output_perturbations(
        self, lna: ArrayLike, modes: Array, args: OutputArgs
    ) -> dict[str, Array]:
        """Output keys: ``delta``, ``theta``, ``sigma`` -- momentum-integrated
        from the binned hierarchy, so directly comparable to the standard
        fluid outputs."""
        BG, params = args
        rho = vmap(self.rho, in_axes=(0, None))(lna, params)  # (Nlna,)
        rhoP = rho + vmap(self.P, in_axes=(0, None))(lna, params)

        rho_delta = vmap(self._rho_delta, in_axes=(0, 1, None))(
            lna, modes, params
        )  # (Nlna, Nk)
        rho_P_theta = vmap(self._rho_plus_P_theta, in_axes=(0, 1, None))(
            lna, modes, params
        )
        rho_P_sigma = vmap(self._rho_plus_P_sigma, in_axes=(0, 1, None))(
            lna, modes, params
        )

        return {
            "delta": rho_delta / rho[:, None],
            "theta": rho_P_theta / rhoP[:, None],
            "sigma": rho_P_sigma / rhoP[:, None],
        }
