r"""
The gauge interface, and the pieces shared by every gauge.

A :class:`Gauge` owns everything about the metric that the rest of the code
would otherwise have to branch on:

* **slot 0 of the state vector** -- the one metric variable that is evolved
  (:math:`\eta` in synchronous gauge, :math:`\phi` in conformal Newtonian
  gauge), its initial value and its derivative;
* **the three fluid-facing source slots** (:class:`~abcmb.metric.MetricSources`),
  which is the entire interface the fluids see;
* **the gauge transformation** of initial conditions written in the other
  gauge;
* **the metric history** stored on the output grid, and the metric-dependent
  pieces of the CMB source functions.

The one gauge-valued thing a fluid may state is
:attr:`~abcmb.species.Fluid.ic_gauge`, which declares the gauge its *own*
``y_ini`` is written in so that this package can convert it. It's there since
people typically write down the ICs in a particular gauge, and for now, its not
worth abstracting that away.

Conventions follow Ma & Bertschinger (1995), ApJ 455, 7
(arXiv:astro-ph/9506072): synchronous :math:`(h, \eta)` from their Eq. (21),
conformal Newtonian :math:`(\phi, \psi)` from their Eq. (23) with
:math:`ds^2 = a^2[-(1+2\psi)d\tau^2 + (1-2\phi)dx^2]`, and the two related by
the generator :math:`\alpha = (h' + 6\eta')/2k^2` of their Eq. (18).

Every prime in this package is ``d/dlna``, matching the rest of ABCMB; the
conformal-time derivatives of the reference equations are recovered by
multiplying by ``aH``.
"""

import warnings
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, ClassVar

import equinox as eqx
import jax.numpy as jnp
from jax import vmap
from jax.typing import ArrayLike
from jaxtyping import Array, Float

from .. import constants as cnst
from ..metric import GaugeName, GaugeShift, MetricSources

if TYPE_CHECKING:
    # Annotations only, for FluidTotals' constructors. Deliberately not a
    # runtime import: gauges must not depend on the fluid machinery
    from ..species import Fluid, PerturbationContext


def _grav(a: ArrayLike) -> Array:
    """
    The :math:`4\\pi G a^2 / c^2` prefactor shared by every Einstein equation
    below, in ABCMB's units (rho in eV cm^-3, lengths in Mpc).
    """
    return 4.0 * jnp.pi * cnst.G * jnp.asarray(a) ** 2 / cnst.c_Mpc_over_s**2


def _shift_from_alpha(
    k: ArrayLike, lna: ArrayLike, aH: ArrayLike, alpha: ArrayLike
) -> GaugeShift:
    r"""
    The :class:`~.metric.GaugeShift` generated by the Ma & Bertschinger
    :math:`\alpha` (metric shear) of their Eq. (18), signed by the caller for the direction
    being applied (re: synchronous to conformal, and vice-versa).
    """
    return GaugeShift(
        delta_per_one_plus_w=-3.0 * jnp.asarray(aH) * alpha,
        theta=jnp.asarray(k) ** 2 * alpha,
        lna=jnp.asarray(lna),
    )


class MetricHistory(eqx.Module):
    """
    Base class for the metric history a gauge writes to the output ``(lna, k)``
    grid, and the return type of :meth:`Gauge.metric_history`.

    It declares no *fields*: each gauge's history is its own variables, and the
    concrete subclasses deliberately share **no** field name, so that code
    written against one gauge's metric raises an ``AttributeError`` when handed
    another's rather than silently reading a different physical quantity.
    """

    def cmb_sources(
        self,
        k: Float[Array, " n_k"],
        aH: Float[Array, "n_lna 1"],
        aH_dot: Float[Array, "n_lna 1"],
        g: Float[Array, "n_lna 1"],
        g_prime: Float[Array, "n_lna 1"],
        expmkappa: Float[Array, "n_lna 1"],
    ) -> "CMBMetricSources":
        """
        The metric-dependent pieces of the CMB source functions, from this
        gauge's own metric variables. ``aH_dot`` is ``d(aH)/dtau``; ``g_prime``
        is ``dg/dlna``.

        See :class:`CMBMetricSources` for the expression these fields are
        substituted into.
        """
        raise NotImplementedError("A metric history must define its CMB source terms.")


class FluidTotals(eqx.Module):
    """
    The stress-energy sums the Einstein equations close on: the fluid side of
    the constraint equations, summed over every species in the model.

    Assembled once per evaluation and handed to the gauge, so that the gauge
    never iterates over species and the species never see a metric variable.

    Attributes:
    -----------
    rho_delta : array
        Sum of ``rho * delta`` (units: eV cm^{-3})
    rho_plus_P_theta : array
        Sum of ``(rho + P) * theta`` (units: eV cm^{-3} Mpc^{-1})
    rho_plus_P_sigma : array
        Sum of ``(rho + P) * sigma`` (units: eV cm^{-3})
    """

    rho_delta: Array
    rho_plus_P_theta: Array
    rho_plus_P_sigma: Array

    @classmethod
    def from_species(
        cls,
        species_list: "tuple[Fluid, ...]",
        lna: ArrayLike,
        y: Array,
        ctx: "PerturbationContext",
    ) -> "FluidTotals":
        """
        Sum the stress-energy of every species at a single ``lna``, from the
        state vector ``y``. This is the form the ODE vector field uses.

        All three sums are always assembled, even though each gauge reads only
        two of them: which ones is the gauge's business, and XLA eliminates the
        unread sum during tracing, so the uniformity is free.
        """
        rho_delta = 0.0
        rho_plus_P_theta = 0.0
        rho_plus_P_sigma = 0.0
        for species in species_list:
            rho_delta += species.rho_delta(lna, y, ctx)
            rho_plus_P_theta += species.rho_plus_P_theta(lna, y, ctx)
            rho_plus_P_sigma += species.rho_plus_P_sigma(lna, y, ctx)
        return cls(
            rho_delta=jnp.asarray(rho_delta),
            rho_plus_P_theta=jnp.asarray(rho_plus_P_theta),
            rho_plus_P_sigma=jnp.asarray(rho_plus_P_sigma),
        )

    @classmethod
    def from_species_on_grid(
        cls,
        species_list: "tuple[Fluid, ...]",
        lna: Float[Array, " n_lna"],
        modes: Float[Array, "n_y n_lna n_k"],
        ctx: "PerturbationContext",
    ) -> "FluidTotals":
        """
        As :meth:`from_species`, batched over the output ``(lna, k)`` grid.

        Species contribute in the same order as :meth:`from_species`, so the
        two agree to the last bit on the same state. Background-only fluids are
        skipped rather than summed as zero: their ``rho_delta`` and friends
        return a Python float, which has no batch axis for ``vmap`` to map.
        """
        zero = jnp.zeros_like(modes[0])
        rho_delta, rho_plus_P_theta, rho_plus_P_sigma = zero, zero, zero
        for s in species_list:
            if s.num_equations == 0:
                continue
            rho_delta = rho_delta + vmap(s.rho_delta, in_axes=(0, 1, None))(
                lna, modes, ctx
            )
            rho_plus_P_theta = rho_plus_P_theta + vmap(
                s.rho_plus_P_theta, in_axes=(0, 1, None)
            )(lna, modes, ctx)
            rho_plus_P_sigma = rho_plus_P_sigma + vmap(
                s.rho_plus_P_sigma, in_axes=(0, 1, None)
            )(lna, modes, ctx)
        return cls(
            rho_delta=rho_delta,
            rho_plus_P_theta=rho_plus_P_theta,
            rho_plus_P_sigma=rho_plus_P_sigma,
        )


class CMBMetricSources(eqx.Module):
    """
    The metric-dependent pieces of the CMB temperature source functions, in
    the form :mod:`abcmb.spectrum` consumes them.

    Splitting the source this way is what lets ``spectrum.py`` stay
    gauge-blind: it supplies the fluid pieces (``delta_g``, ``theta_b``) and
    the visibility function, the gauge supplies these, and the assembled
    ``sourceT0``/``sourceT1`` are the same expressions in both gauges.

    The ISW fields are *complete* contributions -- they already carry their
    own factors of ``g`` and ``exp(-kappa)`` -- because the two gauges group
    those factors differently.

    Attributes:
    -----------
    sw_potential : array
        Added to ``delta_g / 4`` inside the Sachs-Wolfe term.
    isw_T0 : array
        The full integrated Sachs-Wolfe contribution to ``sourceT0``.
    isw_T1 : array
        The full contribution to ``sourceT1``.
    theta_offset : array
        Added to ``theta_b / k^2`` in the Doppler term. This is the shift
        that takes the baryon velocity of the integration gauge to the
        conformal-Newtonian one (zero when that is already the gauge in use).
    theta_offset_prime : array
        ``d/dlna`` of ``theta_offset``, for the ``theta_b_prime`` half of the
        Doppler term.
    """

    sw_potential: Float[Array, "n_lna n_k"]
    isw_T0: Float[Array, "n_lna n_k"]
    isw_T1: Float[Array, "n_lna n_k"]
    theta_offset: Float[Array, "n_lna n_k"]
    theta_offset_prime: Float[Array, "n_lna n_k"]


class Gauge(eqx.Module):
    """
    Base class for the gauges ABCMB can integrate in.
    """

    # The schema-level name of this gauge;
    name: ClassVar[GaugeName]
    # Perturbation-solver tolerances this gauge needs to reach the accuracy
    # ABCMB's defaults deliver in synchronous gauge. Smaller is tighter, so a
    # resolved option *above* one of these is too loose. See check_tolerances.
    recommended_tolerances: ClassVar[dict[str, float]] = {}
    # Companion step budget: the tighter tolerances above need room to be met,
    # and this one is too loose when *below* the recommendation.
    recommended_max_steps: ClassVar[int | None] = None

    def check_tolerances(self, options: "Mapping[str, Any]") -> None:
        """
        Warn if the perturbation solver is set up more loosely than this gauge
        needs.

        ABCMB's default tolerances are tuned against the synchronous gauge --
        in another gauge, they may not converge

        Warning rather than overriding is deliberate
        """
        loose = [
            f"{key}={options[key]!r} (recommended {want!r})"
            for key, want in self.recommended_tolerances.items()
            if key in options and options[key] > want
        ]
        steps = self.recommended_max_steps
        if steps is not None and options.get("max_steps_PE", steps) < steps:
            loose.append(
                f"max_steps_PE={options['max_steps_PE']!r} (recommended {steps!r})"
            )
        if not loose:
            return
        warnings.warn(
            f"the '{self.name}' gauge is running with perturbation-solver "
            f"settings tuned for the synchronous gauge: {', '.join(loose)}. "
            "The defaults are converged in synchronous gauge but not in this "
            "one, where they cost order a percent in P(k) and a few times 1e-3 "
            "in the CMB spectra. Pass the recommended values for results at "
            "ABCMB's usual accuracy.",
            stacklevel=3,
        )

    def metric_y_ini(
        self, aH: ArrayLike, eta_ini: ArrayLike, alpha_ini: ArrayLike
    ) -> Array:
        """
        Initial value of slot 0 of the state vector, given the synchronous
        adiabatic normalization ``eta_ini`` and the gauge generator
        ``alpha_ini`` at the same time.
        """
        raise NotImplementedError("A gauge must define its evolved metric variable.")

    def ic_shift(
        self, k: ArrayLike, lna: ArrayLike, aH: ArrayLike, alpha: ArrayLike
    ) -> GaugeShift:
        """
        The :class:`~.metric.GaugeShift` taking initial conditions *written
        in the other gauge* to this one, signed for this gauge's direction.
        NOTE:  Implicitly assumes that there are only two integration gauges
        (synchronous and conformal).
        """
        raise NotImplementedError("A gauge must define its IC transformation.")

    def sources(
        self,
        k: ArrayLike,
        a: ArrayLike,
        aH: ArrayLike,
        metric_y: ArrayLike,
        totals: FluidTotals,
    ) -> tuple[Array, MetricSources]:
        """
        Close the fluid system: return ``(d(metric_y)/dlna, sources)`` from
        the Einstein constraints, given the summed fluid stress-energy.
        """
        raise NotImplementedError("A gauge must close the Einstein equations.")

    def metric_history(
        self,
        k: ArrayLike,
        a: ArrayLike,
        aH: ArrayLike,
        metric_y: ArrayLike,
        totals: FluidTotals,
    ) -> MetricHistory:
        """
        The gauge's metric variables on the output grid, for
        :attr:`~.perturbations.PerturbationTable.metric`.
        """
        raise NotImplementedError("A gauge must define its output metric history.")
