r"""
Conformal Newtonian (longitudinal) gauge.
"""

from typing import ClassVar

import jax.numpy as jnp
from jax.typing import ArrayLike
from jaxtyping import Array, Float

from ..metric import GaugeName, GaugeShift, MetricSources
from .base import (
    CMBMetricSources,
    FluidTotals,
    Gauge,
    MetricHistory,
    _grav,
    _shift_from_alpha,
)


class NewtonianMetric(MetricHistory):
    """
    The conformal-Newtonian metric history on the output ``(lna, k)`` grid.

    Deliberately shares no field name with
    :class:`~abcmb.gauges.synchronous.SynchronousMetric`: code written against
    one gauge's metric fails loudly with an ``AttributeError`` when handed the
    other's, instead of silently reading a different physical quantity of the
    same name.

    Attributes:
    -----------
    phi : array
        Spatial curvature potential -- the evolved variable (slot 0)
    psi : array
        Newtonian (lapse) potential. Equal to phi up to anisotropic stress
    phi_prime : array
        Time derivative of phi (d/dlna)
    """

    phi: Float[Array, "n_lna n_k"]
    psi: Float[Array, "n_lna n_k"]
    phi_prime: Float[Array, "n_lna n_k"]

    def cmb_sources(
        self,
        k: Float[Array, " n_k"],
        aH: Float[Array, "n_lna 1"],
        aH_dot: Float[Array, "n_lna 1"],
        g: Float[Array, "n_lna 1"],
        g_prime: Float[Array, "n_lna 1"],
        expmkappa: Float[Array, "n_lna 1"],
    ) -> CMBMetricSources:
        """
        CLASS's numerically-efficient Newtonian form: the naive
        ``exp(-kappa) phi' + g delta_g/4`` integrated by parts.

        The Doppler offset is zero -- the evolved ``theta_b`` is already the
        conformal-Newtonian one.
        """
        return CMBMetricSources(
            sw_potential=self.psi,
            isw_T0=(g * (self.phi - self.psi) + 2.0 * expmkappa * aH * self.phi_prime),
            isw_T1=expmkappa * (self.psi - self.phi) * k,
            theta_offset=jnp.zeros_like(self.phi),
            theta_offset_prime=jnp.zeros_like(self.phi),
        )


class NewtonianGauge(Gauge):
    r"""
    Conformal Newtonian (longitudinal) gauge:
    :math:`ds^2 = a^2[-(1+2\psi)d\tau^2 + (1-2\phi)dx^2]`, Ma & Bertschinger
    Eq. (23).
    """

    name: ClassVar[GaugeName] = GaugeName.NEWTONIAN

    # Measured, not guessed: at ABCMB's synchronous-tuned defaults a
    # Newtonian-gauge solve still moves by ~1.4% in P(k) (k > 1e-3) and ~4e-4 in TT when
    # tightened, while a synchronous solve moves by ~1e-4. At these values the
    # two gauges agree to ~3e-3 in P(k) and ~5e-4 in TT, which is the
    # cross-gauge floor set by the solvers.
    recommended_tolerances: ClassVar[dict[str, float]] = {
        "rtol_small_k_PE": 1e-6,
        "rtol_large_k_PE": 1e-5,
        "atol_small_k_PE": 1e-11,
        "atol_large_k_PE": 1e-7,
    }
    recommended_max_steps: ClassVar[int | None] = 32768

    def metric_y_ini(
        self, aH: ArrayLike, eta_ini: ArrayLike, alpha_ini: ArrayLike
    ) -> Array:
        """``phi = eta - aH alpha`` (MB95 Eq. 18)."""
        return jnp.asarray(eta_ini) - aH * alpha_ini

    def ic_shift(
        self, k: ArrayLike, lna: ArrayLike, aH: ArrayLike, alpha: ArrayLike
    ) -> GaugeShift:
        """Synchronous -> conformal Newtonian is generated by ``+alpha``."""
        return _shift_from_alpha(k, lna, aH, jnp.asarray(alpha))

    def sources(
        self,
        k: ArrayLike,
        a: ArrayLike,
        aH: ArrayLike,
        metric_y: ArrayLike,
        totals: FluidTotals,
    ) -> tuple[Array, MetricSources]:
        """
        ``psi`` from the anisotropic-stress constraint and ``phi'`` from the
        momentum constraint (MB95 Eq. 23b, 23d).

        ``shear`` is identically zero here
        """
        grav = _grav(a)
        phi = jnp.asarray(metric_y)
        psi = phi - 3.0 * grav * totals.rho_plus_P_sigma / k**2
        phi_prime = -psi + grav / aH / k**2 * totals.rho_plus_P_theta
        sources = MetricSources(
            continuity=-3.0 * phi_prime,
            euler=k**2 * psi / aH,
            shear=jnp.zeros_like(phi_prime),
        )
        return phi_prime, sources

    def metric_history(
        self,
        k: ArrayLike,
        a: ArrayLike,
        aH: ArrayLike,
        metric_y: ArrayLike,
        totals: FluidTotals,
    ) -> NewtonianMetric:
        """(phi, psi, phi') on the output grid."""
        phi_prime, sources = self.sources(k, a, aH, metric_y, totals)
        # sources.euler is k^2 psi / aH, so psi comes back out of it.
        psi = sources.euler * aH / k**2
        return NewtonianMetric(phi=jnp.asarray(metric_y), psi=psi, phi_prime=phi_prime)
